# Generated by Django 2.2.6 on 2019-12-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftfapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
