# Generated by Django 2.2.4 on 2019-12-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('heartrate', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('dailygoal', models.IntegerField()),
                ('workouttime', models.IntegerField()),
                ('mon', models.IntegerField()),
                ('wed', models.IntegerField()),
                ('thr', models.IntegerField()),
                ('fri', models.IntegerField()),
                ('sat', models.IntegerField()),
                ('sun', models.IntegerField()),
            ],
        ),
    ]
