# Generated by Django 2.2.4 on 2019-12-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tue',
            field=models.IntegerField(default=0),
        ),
    ]
