# Generated by Django 2.2.6 on 2020-01-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_auto_20200119_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
